var express = require('express');
var stormpath = require('express-stormpath');

var app = express();

//sets up middleware for stormpath library
app.use(stormpath.init(app, 
	{
		apiKeyId: process.env.STORMPATH_API_KEY_ID,
		apiKeySecret: process.env.STORMPATH_API_KEY_SECRET,
		secretKey: process.env.STORMPATH_SECRET_KEY,
		application: process.env.STORMPATH_URL,
		website: true,
		//environment variables read from heroku config, once added to your heroku project
	}
));

app.get('/', stormpath.loginRequired, function(req, res){
	//login page auto-generated by stormpath, 2nd get param optional and only if necessary before accessing root
	res.send("This is a Stormpath Heroku Test App. You are now logged in."); 
	//Login via <a href='/login'>login</a> passed into response, also works for a test link to login page
});

app.get('/profile', stormpath.loginRequired, function(req, res){
	//user must be logged in to see their profile details
	res.json(req.user);
});

app.listen(process.env.PORT || 3000);
